<h1>Calculate the Sharpe Ratio</h1>

<h2>Standard Deviation is a measure of volatility</h2>

The Sharpe Ratio is calculated as:

$$
S = \frac{R_p - R_f}{\sigma_p}
$$

Where:
- \( S \) is the Sharpe Ratio
- \( R_p \) is the expected portfolio return
- \( R_f \) is the risk-free rate
- \( \sigma_p \) is the standard deviation of the portfolio's excess return (i.e., its volatility)

In [3]:
import pandas as pd
import numpy as np
import yfinance as yf

In [5]:
start = '2010-01-01'  # Start date for data extraction
end = '2024-09-03'    # End date for data extraction

# Define the stock ticker symbol for Apple Inc.
stock = 'AAPL'        # 'AAPL' is the ticker symbol for Apple Inc. on NASDAQ

# Use the yfinance library to download historical stock data for Apple (AAPL)
# The 'download' method retrieves data between the specified start and end dates
data = yf.download(stock, start, end)

# Reset the index of the DataFrame so that the 'Date' column becomes a regular column
# This makes it easier to work with the data, especially for plotting and analysis
data.reset_index(inplace=True)

# Display the DataFrame containing historical stock data (Open, High, Low, Close, Volume, etc.)
data

[*********************100%***********************]  1 of 1 completed

,Date,Open,High,Low,Close,Adj Close,Volume
0,2010-01-04,7.622500,7.660714,7.585000,7.643214,6.454506,493729600
1,2010-01-05,7.664286,7.699643,7.616071,7.656429,6.465664,601904800
2,2010-01-06,7.656429,7.686786,7.526786,7.534643,6.362819,552160000
3,2010-01-07,7.562500,7.571429,7.466071,7.520714,6.351057,477131200
4,2010-01-08,7.510714,7.571429,7.466429,7.570714,6.393281,447610800
...,...,...,...,...,...,...,...
3685,2024-08-26,226.759995,227.279999,223.889999,227.179993,227.179993,30602200
3686,2024-08-27,226.000000,228.850006,224.889999,228.029999,228.029999,35934600
3687,2024-08-28,227.919998,229.860001,225.679993,226.490005,226.490005,38052200
3688,2024-08-29,230.100006,232.919998,228.880005,229.789993,229.789993,51906300
3689,2024-08-30,230.190002,230.399994,227.479996,229.000000,229.000000,52990800

In [8]:
'''
    The code calculates the day-over-day percentage change in the Adjusted Close price 
    of a stock and stores the result in a new column called 'returns' in the DataFrame.
'''

data['returns'] = data['Adj Close'].pct_change(1)

In [9]:
# Risk-Free Rate
'''
   In practice, no investment is truly risk-free, but government bonds (especially from stable governments) are often used as a proxy for the risk-free rate because they are considered to have the lowest risk of default. For example:
    In the U.S., the 3-month Treasury bill is commonly used as the risk-free rate because it is short-term and backed by the U.S. government.
    Other countries use their equivalent short-term government securities. 
'''
risk_free_rate = 0.02/252

In [10]:
# Excess Returns
'''
    It is used to measure how much additional return an investor 
    is earning by taking on risk, compared to what they would earn from a risk-free investment.
'''
data['excess_returns'] = data['returns'] - risk_free_rate

In [11]:
# Sharpe Ratio
average_excess_return = data['excess_returns'].mean()
std_excess_return = data['excess_returns'].std()

# Annualize for the daily returns
sharpe_ratio = np.sqrt(252) * average_excess_return / std_excess_return

In [12]:
print("Sharpe Ratio:", sharpe_ratio)

Sharpe Ratio: 0.9389864201265256